# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    update_fastlane
  end
  lane :test do
    run_tests(
      workspace: "Signal.xcworkspace", 
      scheme: "Signal", 
      devices: ["iPhone SE"]
    )
  end
  lane :build do
    build_ios_app(
      workspace: "Signal.xcworkspace",
      configuration: "Debug",
      scheme: "Signal",
      silent: true,
      clean: true,
      output_directory: "build", # Destination directory. Defaults to current directory.
      output_name: "Signal.ipa",       # specify the name of the .ipa file to generate (including file extension)
      sdk: "iPhoneOS12.1.sdk" 
    )
  end
end
